### PR TITLE
fix: Pass url string to http.request

### LINKED ISSUE #1267: IPv6 literals are broken
**Reproduction**

```
import fetch from 'node-fetch';
fetch('http://[::1]:8080')
  .then(res => console.debug('ok'))
  .catch(err => console.error('err', err));
```

```
getaddrinfo ENOTFOUND [::1]
```

**Expected behavior**

- If there is a server at `[::1]:8080`, it should not fail

**Cause**

- This was working fine in 2.x, but in 3.x the URL parser switched from Node's `url.Url` to WHATWG's `URL`

```
> u = url.parse('http://[::1]');
Url {
...
  host: '[::1]',
  hostname: '::1',
...
}
> u = new URL('http://[::1]')
URL {
...
  host: '[::1]',
  hostname: '[::1]',
...
}
```

- [offending line, 3.x](https://github.com/node-fetch/node-fetch/blob/914ce6be5ec67a8bab63d68510aabf07cb818b6d/src/request.js#L265) 
- [2.x](https://github.com/node-fetch/node-fetch/blob/b5e2e41b2b50bf2997720d6125accaf0dd68c0ab/src/request.js#L245) passes `url.Url` directly to `request()`

### PR DESCRIPTION
**Pull request by serverwentdown**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Other, please explain:

**What changes did you make? (provide an overview)**

The previous `url.parse` did remove brackets from hostname the `new URL` don't do it.

To fix this i Replaced `https.request(options[, callback])` with `https.request(url[, options][, callback])` and letting NodeJS take care of parsing the the url

- This strips square brackets ([]) off hostnames that have them
- <s>implicit allow basic auth `http://username:password@hostname` that wasn't working before</s>

**Which issue (if any) does this pull request address?**

Closes #1267 

## TODO:

 - [x] Throw if url includes credentials in the constructor<br>TypeError("Request cannot be constructed from a URL that includes credentials")
   - [x] Add test for this

### CODE REVIEW

**Comment by jimmywarting** [comment]
`[]` feels like a very specific usecase

what if we just took the hostname straight from `url.parse` instead? 

`hostname = url.parse(parsedURL.toString()).hostname`

I'm still wondering about just doing: `https.request(url[, options][, callback])` instead of spreading out every single option
and remove the `https.request(options[, callback])` option 

---

not fully rejecting this PR. but i like to have options before finalizing something and explore options

**Comment by serverwentdown** [comment]
This is exactly the [implementation inside the Node.js standard library](https://github.com/nodejs/node/blob/0c35fe02d3b202290ab19d2fc72e914397fdba3d/lib/internal/url.js#L1391), so I'd say it is acceptable.

**Comment by jimmywarting** [comment]
> This is exactly the [implementation inside the Node.js standard library](https://github.com/nodejs/node/blob/0c35fe02d3b202290ab19d2fc72e914397fdba3d/lib/internal/url.js#L1391), so I'd say it is acceptable.

Oh, interesting find.

**Comment by serverwentdown** [comment]
Implementation of your proposal: https://github.com/node-fetch/node-fetch/compare/main...serverwentdown:fix-ipv6-literal-parsing-2

I also added tests for IPv6

**Comment by jimmywarting** [comment]
> Implementation of your proposal: main...serverwentdown:fix-ipv6-literal-parsing-2, though it needs some refactoring (parsedURL and options aren't named well)

Do you want to apply that changes to this PR? 
( Also what do @Richienb, @LinusU, @gr2m (and anybody else) think? ) 

> I also added tests for IPv6 on both proposals.

Great! Needed that!

File: src/request.js [hunk 1]
```diff
@@ -200,6 +200,13 @@ export const getNodeRequestOptions = request => {
 	if (!headers.has('Connection') && !agent) {
 		headers.set('Connection', 'close');
 	}
+	
+	// Because of the differences in paring between Node.js's standard library and WHATWG's spec, IPv6 literal hostnames ([::1]) are treated as domain names by Node.js's standard library.
+	// Strip off the square brackets in WHATWG's URL.hostname before handing it to Node.js.
+	let hostname = parsedURL.hostname;
+	if (hostname.startsWith('[') && hostname.endsWith(']')) {
+		hostname = hostname.substring(1, hostname.length - 1)
+	}
```
Comment (gr2m) [inline src/request.js:209]: Maybe add a reference to this pull request in the comment
```suggestion
	// Because of the differences in paring between Node.js's standard library and WHATWG's spec, IPv6 literal hostnames ([::1]) are treated as domain names by Node.js's standard library.
	// Strip off the square brackets in WHATWG's URL.hostname before handing it to Node.js.
	// See https://github.com/node-fetch/node-fetch/pull/1268
	let hostname = parsedURL.hostname;
	if (hostname.startsWith('[') && hostname.endsWith(']')) {
		hostname = hostname.substring(1, hostname.length - 1)
	}
```

**Review by gr2m — COMMENTED** [review]
Change looks good to me! I'd approve the PR but not sure if there is anything else you want to add

File: src/request.js (hunk 1 above)
Comment (jimmywarting) [reply src/request.js:209]: @gr2m what do you think about using `https.request(url[, options][, callback])` instead of `https.request(options[, callback])` as discussed earlier https://github.com/node-fetch/node-fetch/pull/1268#issuecomment-911880484?

if we do it the other way then this part of the code isn't needed at all and should be removed (replaced with https://github.com/node-fetch/node-fetch/compare/main...serverwentdown:fix-ipv6-literal-parsing-2)
Instead the test-case could references the PR

Comment (gr2m) [reply src/request.js:209]: Oh nice I like that much better!

Comment (jimmywarting) [reply src/request.js:209]: I'm also in fav. of `https.request(url[, options][, callback])` then we simply just let NodeJS core handle it internally

File: src/request.js [hunk 2]
```diff
@@ -206,22 +206,20 @@ export const getNodeRequestOptions = request => {
...
+		// Overwrite search to retain trailing ? (issue #776)
 		path: parsedURL.pathname + search,
-		pathname: parsedURL.pathname,
-		hostname: parsedURL.hostname,
-		protocol: parsedURL.protocol,
-		port: parsedURL.port,
-		hash: parsedURL.hash,
-		search: parsedURL.search,
-		query: parsedURL.query,
-		href: parsedURL.href,
```
Comment (serverwentdown) [inline src/request.js:219]: For those who are curious why these can be removed: 
- Since we're passing the URL to `request()`, we are now using the Node.js standard library URL parser
- The standard library URL parser effectively [expands the URL into the same set of options](https://github.com/nodejs/node/blob/1c4df352b77514e93a46fb27e996755d45a0b530/lib/internal/url.js#L1388).

Comment (serverwentdown) [reply src/request.js:219]: Oh! This led me to a side effect of this PRs' changes: [Basic auth](https://github.com/nodejs/node/blob/1c4df352b77514e93a46fb27e996755d45a0b530/lib/internal/url.js#L1405) (`username:password@hostname`) is now supported implictly by `node-fetch`. 

Should this be a concern?

Seems to be allowed in the [`fetch()` spec, §4.2 step 8.19.2.3.](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch)

**Review by LinusU — APPROVED** [review]
I think that this seems like a great approach 👍

**Comment by gr2m** [comment]
can you address the lint errors?

image


Running `npx xo --fix` should address them all

File: src/request.js (hunk 2 above)
Comment (jimmywarting) [reply src/request.js:219]: 👍

**Comment by serverwentdown** [comment]
Turns out the `fetch()` spec lists basic auth, but is not implemented by any browsers for security reasons. But, allowing basic auth should be useful for majority of applications.

**Review by jimmywarting — APPROVED** [review]

**Comment by jimmywarting** [comment]
Started to get 2nd toughs on supporting basic auth...

Starting looking more into the `isAuthenticationFetch` in the spec and also trying it out in chromes devtool
image

Guess it have something to do with caching... it's bad to use [cache storage](https://developer.mozilla.org/en-US/docs/Web/API/Cache) and save the username & text in full plain text (url)

- the usr/psw should be converted to a basic auth request header to avoid saving the headers to the cache storage.
- It's also b/c the usr:psw should not be exposed in the `response.url` (for security reasons)

We could argue that we don't have the same level of restrictions and we don't have a cache storage.

I guess the `isAuthenticationFetch` flag is mostly set to true when working with mitm service workers and you get prompted with that builtin old basic auth login dialog in the browsers.

We also have a hole option with `credentials` that we haven't looked into much at all in node-fetch
`new Request(url, { credentials: 'include' })`

> credentials: The request credentials you want to use for the request: omit, same-origin, or include. The default is same-origin.

we don't have a concept of origin either.

Either way i still think this PR looks good question is wether or not we shoud:
- ...also throw an error when constructing the Request with a url that includes credentials
- or if we should auto "converted to an `Authorization` value" as mention in the spec also and strip away the usr/psw from the url
- or just simply allow it

we could also start having a look at what the credential option is

**Comment by jimmywarting** [comment]
fyi. i tried deno's built in fetch api also... `fetch('https://foo:bar@vecka.nu', {credentials: 'include'})` worked out fine

**Comment by jimmywarting** [comment]
@node-fetch/reviewers Should we throw an error for the time being on basic-auth-url? 
it's easier to lift the restriction rather than removing/deprecating/discourage it.

Our ambition is that the code you write should be working everywhere the same way in Deno, Node & Browsers.
And if non of the browsers allow it then everyone should be using the solution that works cross all platforms. Meaning: using btoa and appending basic auth headers & throwing an error like browser dose.

**Comment by gr2m** [comment]
> Our ambition is that the code you write should be working everywhere the same way in Deno, Node & Browsers.
> And if non of the browsers allow it then everyone should be using the solution that works cross all platforms

I concur

File: docs/v3-LIMITS.md [hunk 3]
```diff
@@ -7,6 +7,8 @@ Known differences
 
 - On the upside, there are no forbidden headers.
 
+- Passing basic authentication credentials (`https://username:password@hostname`) in the URL is supported.
```
Comment (jimmywarting) [inline docs/v3-LIMITS.md:10]: For now lets just throw a TypeError if url includes credentials in the Request constructor.
We can decide later what to do with it. Want to find out what the real reason is first.

**Review by jimmywarting — CHANGES_REQUESTED** [review]

**Comment by serverwentdown** [comment]
I also realised that the specification somewhat contradicts: when creating a `Request` with a URL that includes credentials, it [should throw a `TypeError`](https://fetch.spec.whatwg.org/#ref-for-include-credentials④).

**Review by jimmywarting — APPROVED** [review]

**Comment by jimmywarting** [comment]
Thanks for your contribution to node fetch
It will be released in the next version.

I don't have the possibility to make a release yet until Sunday
I'm on a vacation now with no computer. Unless someone else dose it...

Would be nice to have that auto ci deployment now...

**Comment by jimmywarting** [comment]
@serverwentdown If you would like to help out more with one other issue then i got something easy for you. (You don't have to if you don't want)

If a Request is constructed with method HEAD or GET then delete content-length request header #1249

**Comment by lachesis** [comment]
This change to reject implicit basic-auth breaks our use case. We will not upgrade node-fetch past v2 until or unless this is fixed.
