### PR TITLE
fix v2.6.3 that did not send query params

### LINKED ISSUE #1300: Problem with query params
**Reproduction**

When using node-fetch version 2.6.3, making a request to http://nginx/transactions/total?month=2021-09 do not send the url params. If I am using node-fetch version 2.6.1 everything work fine. Enabling node http verbose log, when making the request using node-fetch version 2.6.1 I get:

```
HTTP 52: createConnection nginx:80: {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'nginx',
  port: 80,
  hostname: 'nginx',
  hash: null,
  search: '?month=2021-09',
  query: 'month=2021-09',
  pathname: '/api/transactions/total',
  path: null,
  href: 'http://nginx/api/transactions/total?month=2021-09',
  method: 'GET',
  headers: [Object: null prototype] {
    Authorization: [
      'Bearer ....'
    ],
    Accept: [ '*/*' ],
    'User-Agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
    'Accept-Encoding': [ 'gzip,deflate' ],
    Connection: [ 'close' ]
  },
  agent: undefined,
  servername: 'nginx',
  _agentKey: 'nginx:80:'
}
```

but using node-fetch version 2.6.3 I get

```
HTTP 24: createConnection nginx:80: {
  path: null,
  pathname: '/api/transactions/total',
  hostname: 'nginx',
  protocol: 'http:',
  port: 80,
  hash: '',
  search: '?month=2021-09',
  query: undefined,
  href: 'http://nginx/api/transactions/total?month=2021-09',
  method: 'GET',
  headers: [Object: null prototype] {
    Authorization: [
      'Bearer ....
    ],
    Accept: [ '*/*' ],
    'User-Agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
    'Accept-Encoding': [ 'gzip,deflate' ],
    Connection: [ 'close' ]
  },
  agent: undefined,
  host: 'nginx',
  servername: 'nginx',
  _agentKey: 'nginx:80:'
}
```

Note the query part is undefined when using node-fetch version 2.6.3.

**Expected behavior**

The behaviour of the two versions should be the same.

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.3
| node             | 14.17.3
| npm              | 6.14.3
| Operating System | linux

**Additional context**

### PR DESCRIPTION
**Pull request by jimmywarting**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Other, please explain:

closes #1300

### CODE REVIEW

**Comment by jimmywarting** [comment]
This was more then what i wanted to do... making a new PR

**Comment by jimmywarting** [comment]
This have already been released to npm
had to get it out quickly, it was breaking a few things.

**Review by LinusU — APPROVED** [review]
Thank you for the quick follow up on this! ❤️

File: test/test.js [hunk 1]
```diff
@@ -2847,6 +2847,15 @@ describe('external encoding', () => {
...
 describe('issue #1290', function() {
+
+	it('should keep query params', function() {
+		return fetch(`${base}inspect?month=2021-09`)
+		  .then(res => res.json())
+			.then(json => {
+				expect(json.url).to.equal('/inspect?month=2021-09')
+			})
+	})
+
```
Comment (gr2m) [inline test/test.js:2858]: thanks for putting in a test to avoid future regressions 💐 

This explains the mystery of https://github.com/octokit/rest.js/issues/114 and https://github.com/semantic-release/github/issues/415
