### PR TITLE
fix: socket variable testing for undefined

### LINKED ISSUE #1725: Deno process crashes while using node-fetch 2.x.x
Using deno (which now supports npm packages) and node-fetch 2.x.x yields an unhandled error due to "socket" event not being triggered.

I believe keeping deno compatibility is not a priority but a simple `undefined` testing in the socket variable should fix the issue.

**Reproduction**

1. Use deno and node-fetch
2. Perform a simple fetch operation (ex: GET)
3. Verify that the deno process has exited with an Uncaught error on `fixResponseChunkedTransferBadEnding()`

**Expected behavior**

No unhandled error is raised and the fetch requests are handled properly.

**Screenshots**

image

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | v2.6.8+
| deno            | v1.31.3
| Operating System | Windows

**Additional context**

This is verified only while using deno and not in node.js.

### PR DESCRIPTION
**Pull request by joamag**
Avoid issue where socket event was not triggered and local socket variable is not defined. This issue is reproducible only using deno.

## Purpose

#1725

## Changes

Adds undefined testing to socket variable, protecting it from TypeError.

___

- fix #1725

### CODE REVIEW

**Comment by joamag** [comment]
@jimmywarting do you think you can merge this one? It's a simple undefined validation 🙏

**Comment by joamag** [comment]
@jimmywarting bump ;)

**Comment by jimmywarting** [comment]
```js
	request.on('response', response => {
		const {headers} = response;
		if (headers['transfer-encoding'] === 'chunked' && !headers['content-length']) {
			response.once('close', hadError => {
				// if for some reason the 'socket' event was not triggered
				// for the request (happens in deno) avoids `TypeError`
				if (socket === undefined) {
					return;
				}

				// if a data listener is still present we didn't end cleanly
				const hasDataListener = socket.listenerCount('data') > 0;

				if (hasDataListener && !hadError) {
					const err = new Error('Premature close');
					err.code = 'ERR_STREAM_PREMATURE_CLOSE';
					errorCallback(err);
				}
			});
		}
	});
```

don't we still want to handle `close` callback at what is at the bottom?
aka:
```js
				if (hasDataListener && !hadError) {
					const err = new Error('Premature close');
					err.code = 'ERR_STREAM_PREMATURE_CLOSE';
					errorCallback(err);
				}
```
maybe would be better to just do:
```js
				// if for some reason the 'socket' event was not triggered
				// for the request (happens in deno) avoids `TypeError`
				if (socket) {
				    // if a data listener is still present we didn't end cleanly
				    const hasDataListener = socket.listenerCount('data') > 0;
				}
```

**Comment by joamag** [comment]
> ```js
> 	request.on('response', response => {
> 		const {headers} = response;
> 		if (headers['transfer-encoding'] === 'chunked' && !headers['content-length']) {
> 			response.once('close', hadError => {
> 				// if for some reason the 'socket' event was not triggered
> 				// for the request (happens in deno) avoids `TypeError`
> 				if (socket === undefined) {
> 					return;
> 				}
> 
> 				// if a data listener is still present we didn't end cleanly
> 				const hasDataListener = socket.listenerCount('data') > 0;
> 
> 				if (hasDataListener && !hadError) {
> 					const err = new Error('Premature close');
> 					err.code = 'ERR_STREAM_PREMATURE_CLOSE';
> 					errorCallback(err);
> 				}
> 			});
> 		}
> 	});
> ```
> 
> don't we still want to handle `close` callback at what is at the bottom? aka:
> 
> ```js
> 				if (hasDataListener && !hadError) {
> 					const err = new Error('Premature close');
> 					err.code = 'ERR_STREAM_PREMATURE_CLOSE';
> 					errorCallback(err);
> 				}
> ```
> 
> maybe would be better to just do:
> 
> ```js
> 				// if for some reason the 'socket' event was not triggered
> 				// for the request (happens in deno) avoids `TypeError`
> 				if (socket) {
> 				    // if a data listener is still present we didn't end cleanly
> 				    const hasDataListener = socket.listenerCount('data') > 0;
> 				}
> ```

Yes it makes more sense.
It's done 👍

File: src/index.js [hunk 1]
```diff
@@ -362,8 +362,13 @@ function fixResponseChunkedTransferBadEnding(request, errorCallback) {
...
 			response.once('close', hadError => {
-				// if a data listener is still present we didn't end cleanly
-				const hasDataListener = socket.listenerCount('data') > 0;
+				// tests for socket presence, as in some situations the
+				// the 'socket' event is not triggered for the request
+				// (happens in deno), avoids `TypeError`
+				if (socket !== undefined) {
+					// if a data listener is still present we didn't end cleanly
+					const hasDataListener = socket.listenerCount('data') > 0;
+				}
```
Comment (LinusU) [inline src/index.js:371]: This `const` declaration only exists within the if statements scope, and not outside it where it's later being used

```suggestion
                                let hasDataListener
				if (socket !== undefined) {
					// if a data listener is still present we didn't end cleanly
					hasDataListener = socket.listenerCount('data') > 0;
				}
```

**Comment by joamag** [comment]
@jimmywarting should be ready for merge 😀

**Comment by joamag** [comment]
@LinusU Can you the this PR, it would be super useful to have this one merged :) 🙏

**Review by jimmywarting — APPROVED** [review]
